export const attributesDisplayNames: Record<string, string> = {
  activity: "Activity (Sector Code)",
  size: "Company Size",
  "net.sales": "Net Sales",
  "cost.of.goods.and.services": "Cost of Goods and Services",
  "cost.of.labor": "Cost of Labor",
  depreciation: "Depreciation",
  "financial.expenses": "Financial Expenses",
  interest: "Interest Expenses",
  EBIT: "EBIT",
  EBITDA: "EBITDA",
  "net.income": "Net Income",
  assets: "Total Assets",
  equity: "Equity",
  debt: "Debt",
  cash: "Cash",
  "lt.assets": "Long-Term Assets",
  "st.assets": "Short-Term Assets",
  "total.oper.liabilities": "Total Operating Liabilities",
  "st.oper.liabilities": "Short-Term Operating Liabilities",
  "lt.liabilities": "Long-Term Liabilities",
  "st.liabilities": "Short-Term Liabilities",
  inventories: "Inventories",
  FFO: "Funds From Operations (FFO)",
  OCF: "Operating Cash Flow (OCF)",
  "total.oper.liabilities/assets": "Operating Liabilities to Assets Ratio [%]",
  "current.ratio": "Current Ratio",
  "lt.sales.growth": "Long-Term Sales Growth [%]",
  "st.sales.growth": "Short-Term Sales Growth [%]",
  "lt.ebit.margin.change": "Long-Term EBIT Margin Change [%]",
  "net.debt/EBITDA": "Net Debt to EBITDA",
  "equity.ratio": "Equity Ratio",
  TIE: "Times Interest Earned",
  ROA: "Return on Assets [%]",
  public: "Public Ownership",
  "credit.score": "Credit Score",
};

export const tooltipDescriptions: Record<string, string> = {
  "net.sales":
    "Sales value of products, goods, materials, and services performed during the accounting period.",
  "cost.of.goods.and.services":
    "Costs of goods and materials sold, consumed materials, and service costs.",
  "cost.of.labor":
    "Costs related to wages, wage compensation, and related levies.",
  depreciation:
    "Amortization and revaluation of depreciable assets like receivables.",
  "financial.expenses":
    "Financing and investment expenses including interests and revaluations.",
  interest: "Financial expenses specifically representing interest payments.",
  EBIT: "Operating profit before interest and taxes (EBIT = EBITDA - Depreciation).",
  EBITDA: "Earnings before interest, taxes, depreciation, and amortization.",
  "net.income":
    "Difference between total revenue and total expenses minus taxes.",
  assets: "Total assets the company owns (balance sheet size).",
  equity: "Company's own capital (Assets - Liabilities).",
  debt: "Sum of short-term and long-term financial obligations.",
  cash: "Cash, bank balances, highly liquid securities.",
  "lt.assets":
    "Non-current assets like real estate, intangibles, long-term receivables.",
  "st.assets": "Inventory, cash, receivables due within a year.",
  "total.oper.liabilities":
    "Obligations from business operations: suppliers, taxes, employees.",
  "st.oper.liabilities": "Operating debts due within one year.",
  "lt.liabilities": "Obligations due after one year.",
  "st.liabilities": "Short-term loans, debts, and payables.",
  inventories: "Goods, materials held for sale or production.",
  FFO: "Net Income plus Depreciation — cash flow from core business.",
  OCF: "Adjusted cash flow considering working capital changes.",
  "net.debt/EBITDA": "Debt burden relative to operating earnings; risk if >4.",
  "current.ratio": "Liquidity ratio; ability to pay short-term obligations.",
  "total.oper.liabilities/asset": "Share of operating debts in total assets.",
  ROA: "Efficiency of asset usage to generate profits.",
  TIE: "How many times EBIT covers interest expenses.",
  "equity.ratio": "Portion of assets financed through owners' equity.",
};

export const eurAttr = [
  "net.sales",
  "cost.of.goods.and.services",
  "cost.of.labor",
  "depreciation",
  "financial.expenses",
  "interest",
  "EBIT",
  "EBITDA",
  "net.income",
  "assets",
  "equity",
  "debt",
  "cash",
  "lt.assets",
  "st.assets",
  "total.oper.liabilities",
  "st.oper.liabilities",
  "lt.liabilities",
  "st.liabilities",
  "inventories",
  "FFO",
  "OCF",
];

export const attributeGroups = {
  "Income Statement": [
    "net.sales",
    "cost.of.goods.and.services",
    "cost.of.labor",
    "depreciation",
    "financial.expenses",
    "interest",
    "EBIT",
    "EBITDA",
    "net.income",
  ],
  "Balance Sheet": [
    "assets",
    "equity",
    "debt",
    "cash",
    "lt.assets",
    "st.assets",
    "total.oper.liabilities",
    "st.oper.liabilities",
    "lt.liabilities",
    "st.liabilities",
    "inventories",
  ],
  "Cash Flow": ["FFO", "OCF"],
  Ratios: [
    "total.oper.liabilities/assets",
    "current.ratio",
    "lt.sales.growth",
    "st.sales.growth",
    "lt.ebit.margin.change",
    "net.debt/EBITDA",
    "equity.ratio",
    "TIE",
    "ROA",
    "public",
  ],
};
